# Generated by Django 5.2.10 on 2026-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='CWMS System', max_length=255)),
                ('short_name', models.CharField(default='CWMS', max_length=50)),
                ('product_name', models.CharField(default='Construction Workforce Management', max_length=255)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_gstin', models.CharField(blank=True, default='', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'Brand Setting',
                'verbose_name_plural': 'Brand Settings',
            },
        ),
    ]
