# Generated by Django 5.2.10 on 2026-06-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_brandsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='king_logo',
            field=models.ImageField(blank=True, help_text='Used for the restricted Owner Console (Gold Theme)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='brandsettings',
            name='portal_logo',
            field=models.ImageField(blank=True, help_text='Used for the Manager/Worker login and PDFs (Blue Theme)', null=True, upload_to='branding/'),
        ),
    ]
