# Generated by Django 5.2.10 on 2026-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_on',
            field=models.DateField(blank=True, help_text='Date when bill was paid', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pdf_file',
            field=models.FileField(upload_to='billing/billing_pdfs/'),
        ),
    ]
