# Generated by Django 5.2.10 on 2026-03-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_paid_on_alter_bill_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Optional PDF file for the bill', null=True, upload_to='billing/billing_pdfs/'),
        ),
    ]
