# Generated by Django 5.2.10 on 2026-04-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('client', 'Credit Customer'), ('debtor', 'Debtor')], db_index=True, default='debtor', help_text='client = incoming money, debtor = outgoing money', max_length=20),
        ),
    ]
