# Generated by Django 5.2.10 on 2026-04-01 14:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_aadhar_number_employee_bank_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('PERMANENT', 'Permanent')], default='LOCAL', help_text='Local = daily wage only. Permanent = subject to PF/ESIC deductions.', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='esic_applicable',
            field=models.BooleanField(default=False, help_text='If True, ESIC will be deducted during payroll generation.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='esic_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0075'), help_text='Employee ESIC contribution rate. Default 0.75% = 0.0075', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_applicable',
            field=models.BooleanField(default=False, help_text='If True, PF will be deducted during payroll generation.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.1200'), help_text='Employee PF contribution rate. Default 12% = 0.1200', max_digits=5),
        ),
    ]
