# Generated by Django 5.2.10 on 2026-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='site',
            field=models.CharField(choices=[('raigarh', 'Raigarh'), ('bhilai', 'Bhilai')], default='raigarh', help_text='Work location of this employee', max_length=100),
        ),
    ]
