# Generated by Django 5.2.10 on 2026-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=models.CharField(choices=[('raigarh', 'Raigarh'), ('bhilai', 'Bhilai'), ('korba', 'Korba'), ('jharkhand', 'Jharkhand'), ('durg', 'Durg')], default='raigarh', help_text='Work location of this employee', max_length=100),
        ),
    ]
