# Generated by Django 5.2.10 on 2026-03-29 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username snapshot', max_length=150)),
                ('user_role', models.CharField(blank=True, help_text='King or Manager role at time of action', max_length=50)),
                ('activity', models.CharField(choices=[('attendance', 'Attendance'), ('payroll', 'Payroll'), ('expense', 'Expense'), ('bill', 'Bill'), ('employee', 'Employee'), ('user', 'User'), ('workorder', 'Work Order'), ('revenue', 'Revenue'), ('system', 'System')], db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('mark_paid', 'Marked as Paid'), ('mark_present', 'Marked Present'), ('mark_absent', 'Marked Absent'), ('mark_halfday', 'Marked Half-day'), ('generate', 'Generated'), ('issue', 'Issued'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Exported'), ('other', 'Other')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(db_index=True, help_text='Employee, MonthlySalary, Attendance, etc.', max_length=50)),
                ('entity_id', models.IntegerField(db_index=True, help_text='Primary key of affected entity')),
                ('entity_name', models.CharField(blank=True, help_text='Human-readable name of affected entity', max_length=255)),
                ('details', models.TextField(blank=True, help_text='JSON or text summary of what changed')),
                ('old_values', models.TextField(blank=True, help_text='Previous values (for updates)')),
                ('new_values', models.TextField(blank=True, help_text='New values set')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of requester', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='If status is error, what went wrong')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_a_timesta_cedd04_idx'), models.Index(fields=['user', '-timestamp'], name='analytics_a_user_id_179d10_idx'), models.Index(fields=['activity', '-timestamp'], name='analytics_a_activit_992e49_idx'), models.Index(fields=['entity_type', 'entity_id'], name='analytics_a_entity__9ea020_idx')],
            },
        ),
    ]
