# Generated by Django 5.2.10 on 2026-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('fuel', 'Fuel'), ('travel', 'Travel'), ('material', 'Material'), ('misc', 'Misc'), ('room_rent', 'Room Rent'), ('gate_pass_medical', 'Gate Pass & Medical'), ('vehicle_rent', 'Vehicle Rent'), ('hotel_stay', 'Hotel Stay'), ('stationary', 'Stationary'), ('vehicle_repair', 'Vehicle Repair'), ('vehicle_transport', 'Vehicle Transport'), ('worker_transport', 'Worker Transport')], max_length=30),
        ),
    ]
