# Generated by Django 5.2.10 on 2026-05-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0003_rename_voucher_no_and_enforce_ledger_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Branch Code'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='buyer_name_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Buyer Name'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='gst_snapshot',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GST No.'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='party_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Party Name'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='Value Date'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='wo_number_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WO Number'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='king.workorder', verbose_name='Linked Work Order'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='particulars',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref No. / Cheque No.'),
        ),
    ]
