# Generated by Django 5.2.10 on 2026-05-16 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king', '0004_ledgerentry_branch_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='buyer_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='gst_snapshot',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='party_name',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='wo_number_snapshot',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='particulars',
            field=models.CharField(max_length=255, verbose_name='Particulars'),
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Party Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_accounts', to='king.workorder', verbose_name='Linked Work Order')),
            ],
            options={
                'verbose_name': 'Ledger Account',
                'verbose_name_plural': 'Ledger Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='king.ledgeraccount', verbose_name='Account / Party'),
        ),
    ]
