"""Django settings for CWMS.

Module: config.settings
App: config
Purpose: Central runtime configuration for all Django apps in CWMS.
Key responsibilities: Configure security, apps, middleware, DB, cache, and
static/media settings.
Dependencies: Environment variables, Django core settings, app middleware stack.
Author note: This file currently prioritizes local development convenience;
production hardening must be applied before deployment.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from decouple import config

# ============================================================
# CORE PATHS
# ============================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# WARNING: Hardcoded secret key is acceptable only for local/dev usage.
# PRODUCTION: Load SECRET_KEY exclusively from environment/secret manager.
# ============================================================
# SECURITY & DEBUG CONFIGURATION
# ============================================================

# Load values cleanly using python-decouple's config tool
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000'
).split(',')



# Application definition

# INSTALLED_APPS: Domain modules are separated by business function
# (employees, attendance, payroll, etc.).
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'employees.apps.EmployeesConfig',

    'attendance',

    'payroll',

    'portal',

    'billing',

    'expenses.apps.ExpensesConfig',

    'analytics.apps.AnalyticsConfig',

    'king.apps.KingConfig',

    'rest_framework',

    'drf_spectacular',

    # Only load dev tools in DEBUG mode
    *(['django_extensions'] if DEBUG else []),

    'leaves',


]

# MIDDLEWARE: Includes request context middleware so signals/audit services can
# access request/user metadata.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'analytics.request_context.CurrentRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# SECURITY: SQLite is suitable for local/dev. Use managed PostgreSQL/MySQL in
# production.
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600
    )
}

# ============================================================
# REDIS CACHE CONFIGURATION
# ============================================================
REDIS_URL = config('REDIS_URL', default=None)

if not REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
            },
            "KEY_PREFIX": "cwms",
            "TIMEOUT": 300,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# PRODUCTION: Serve via CDN/whitenoise/web server; do not rely on Django dev
# static serving.
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirects for Login/Logout
LOGIN_URL = 'portal_login'          # <--- Redirects unauthenticated users here
LOGIN_REDIRECT_URL = 'portal_login' # <--- Where to go after login (handled in views)

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# WARNING: Render free tier has ephemeral storage
# Media files uploaded by users will be lost on redeploy
# TODO Week 4: Migrate to Cloudinary or AWS S3 for persistent media storage

# ============================================================
# DYNAMIC BRANDING CONFIGURATION
# ============================================================
BRAND_COMPANY_NAME = config('BRAND_COMPANY_NAME', default='Sakuntalam India Services')
BRAND_SHORT_NAME = config('BRAND_SHORT_NAME', default='CWMS')
BRAND_PRODUCT_NAME = config('BRAND_PRODUCT_NAME', default='Construction Workforce Management')
BRAND_ACCOUNT_NAME = config('BRAND_ACCOUNT_NAME', default=BRAND_COMPANY_NAME.upper())
BRAND_COMPANY_ADDRESS = config('BRAND_COMPANY_ADDRESS', default='')
BRAND_COMPANY_GSTIN = config('BRAND_COMPANY_GSTIN', default='')



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CWMS API',
    'DESCRIPTION': 'Contractor Workforce Management System API',
    'VERSION': '1.0.0',
    'SECURITY': [{'bearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}

# Production Security Settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_AGE = 86400  # 24 hours
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
