# Generated by Django 5.2.10 on 2026-05-08 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employee_aadhar_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('LOCAL', 'Local')], max_length=20, unique=True)),
                ('annual_leave_days', models.PositiveIntegerField(help_text='Total leave days per calendar year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Leave Policies',
            },
        ),
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('total_days', models.PositiveIntegerField()),
                ('used_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_allocations', to='employees.employee')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('department', models.CharField(blank=True, help_text='Department or site name', max_length=100)),
                ('leave_type', models.CharField(choices=[('EL', 'Earned Leave'), ('CL', 'Casual Leave'), ('SL', 'Sick Leave')], max_length=5)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('address_on_leave', models.TextField(blank=True, help_text="Worker's address/contact during leave")),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('cancelled', 'Cancelled')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_records', to='leaves.leaveallocation')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
    ]
