# Generated by Django 5.2.10 on 2026-02-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_on',
            field=models.DateField(blank=True, help_text='Date when payment was made', null=True),
        ),
    ]
