# Generated by Django 5.2.10 on 2026-04-01 14:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_monthlysalary_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='esic_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ESIC amount deducted this month.', max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='esic_rate_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='ESIC rate in effect at time of payroll generation. For audit trail.', max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='pf_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PF amount deducted this month.', max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='pf_rate_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='PF rate in effect at time of payroll generation. For audit trail.', max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of advance + PF + ESIC deductions.', max_digits=10),
        ),
    ]
