# Generated by Django 5.2.10 on 2026-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_add_pf_esic_deduction_fields_to_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
