# Generated by Django 5.2.10 on 2026-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_advance_settled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], help_text='Payment method used to disburse this salary', max_length=20, null=True),
        ),
    ]
