"""
payroll/models.py

Defines the core financial models for CWMS payroll system.

Models:
    - Advance: Tracks cash loans issued to employees with FIFO recovery support.
    - MonthlySalary: Immutable salary snapshot generated each month per employee.

ARCHITECTURAL RULE:
    These models are dumb data containers.
    All financial calculations MUST live in payroll/services.py.
    Models only enforce data integrity via validators and clean().
"""


from django.db import models
from decimal import Decimal
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.utils import timezone
from employees.models import Employee

# ============================================================
# 1. ADVANCE MODEL
# Tracks cash loans issued to employees.
# Recovery happens automatically during payroll via FIFO logic
# in payroll/services.py — NOT here.
# ============================================================

class Advance(models.Model):
    """
    Represents a single cash advance (loan) issued to an employee.

    Fields:
        employee        — The employee who received the advance.
        amount          — Original loan amount (immutable after creation).
        remaining_amount — Outstanding unpaid balance (reduces as payroll deducts).
        issued_date     — Date the advance was issued (used for FIFO ordering).
        settled         — True when remaining_amount reaches 0.
        created_at      — Timestamp of record creation.

    Ordering:
        By issued_date ascending — ensures FIFO deduction (oldest advance first).
    """ 
    employee = models.ForeignKey(
        Employee,
        on_delete=models.PROTECT,        # Prevent accidental employee deletion if advances exist
        related_name="advances"
    )

    # Financial Safety: Prevent zero or negative advance amounts
    amount = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        validators=[MinValueValidator(0.01)] 
    )
    
    # Tracks how much of the advance is still unpaid
    remaining_amount = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        validators=[MinValueValidator(0.00)]
    )

    issued_date = models.DateField()
    settled = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["issued_date"]   # FIFO: oldest advances are deducted first


    def __str__(self):
        status = "Settled" if self.settled else "Active"
        return f"Advance ₹{self.amount} for {self.employee} ({status})"

    def clean(self):
        """
        Model-level business rule validation.
        Called automatically by full_clean() before every save.
        """ 
         # Rule: Remaining balance cannot exceed the original loan amount
        if self.remaining_amount is not None and self.amount is not None:
            if self.remaining_amount > self.amount:
                raise ValidationError("Remaining amount cannot be greater than original amount.")
        
        # Rule: Auto-settle if remaining balance is zero
        if self.remaining_amount == 0 and not self.settled:
            self.settled = True
            
    def save(self, *args, **kwargs):
        """
        Custom save logic:
        - Auto-fills remaining_amount on first creation.
        - Forces full_clean() to run validation before persisting.
        """
         # On creation: remaining balance starts as the full advance amount
        if self._state.adding and self.remaining_amount is None:
            self.remaining_amount = self.amount
        
        self.full_clean() # Force all validation before saving
        super().save(*args, **kwargs)


# ============================================================
# 2. MONTHLY SALARY MODEL
# Immutable payroll snapshot generated once per employee per month.
# After generation, this record must NOT be modified for financial
# integrity (audit trail).
# Marking as paid only updates is_paid and paid_on fields.
# ============================================================

class MonthlySalary(models.Model):
    """
    Immutable salary snapshot for one employee for one calendar month.

    Generated by payroll/services.py::generate_monthly_salary().
    Views and templates MUST NOT modify financial fields after creation.

    Fields:
        employee            — The employee this salary belongs to.
        month               — First day of the salary month (e.g. 2025-01-01 for Jan 2025).
        days_present        — Count of fully present days that month.
        half_days           — Count of half-day attendance records.
        paid_leaves         — Number of absences covered as paid leave (max 2 per month).
        overtime_hours      — Total overtime hours logged that month.
        gross_pay           — Total earnings before advance deduction.
        advance_deducted    — Amount recovered from outstanding advances (FIFO).
        net_pay             — Final take-home amount (gross_pay - advance_deducted).
        remaining_advance   — Total outstanding advance balance after this payroll.
        is_paid             — Whether the salary has been physically disbursed.
        paid_on             — Date of actual payment.
        generated_at        — Timestamp of salary generation.

    Constraints:
        One salary record per employee per month (enforced at DB level).
    """
    employee = models.ForeignKey(
        Employee,
        on_delete=models.PROTECT, # Protect historical records from accidental deletion
        related_name='monthly_salaries'
    )
    # Always store as first day of month: e.g. date(2025, 1, 1) for January 2025
    month = models.DateField(help_text="Use first day of the month")
    
    # Attendance breakdown used in gross pay calculation
    days_present = models.PositiveIntegerField(default=0)
    half_days = models.PositiveIntegerField(default=0) 
    paid_leaves = models.PositiveIntegerField(default=0)
    overtime_hours = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    

    # Financial snapshot (immutable after generation)
    gross_pay = models.DecimalField(max_digits=10, decimal_places=2)
    advance_deducted = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    pf_deduction = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text="PF amount deducted this month."
    )
    esic_deduction = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text="ESIC amount deducted this month."
    )
    pf_rate_snapshot = models.DecimalField(
        max_digits=5,
        decimal_places=4,
        default=Decimal('0.0000'),
        help_text="PF rate in effect at time of payroll generation. For audit trail."
    )
    esic_rate_snapshot = models.DecimalField(
        max_digits=5,
        decimal_places=4,
        default=Decimal('0.0000'),
        help_text="ESIC rate in effect at time of payroll generation. For audit trail."
    )
    total_deductions = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text="Sum of advance + PF + ESIC deductions."
    )

    net_pay = models.DecimalField(max_digits=10, decimal_places=2)
    remaining_advance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    # Payment tracking fields
    is_paid = models.BooleanField(default=False)
    
    # ⬇️ FIX 1: ADDED MISSING FIELD
    paid_on = models.DateField(null=True, blank=True, help_text="Date when payment was made")
    
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Monthly Salary"
        verbose_name_plural = "Monthly Salaries"
        constraints = [
            # Enforce one salary record per employee per month at database level
            models.UniqueConstraint(
                fields=['employee', 'month'],
                name='unique_salary_per_employee_per_month'
            )
        ]

    def clean(self):
        """Ensure month consistency and financial integrity for admin/non-service writes."""
        parent_clean = getattr(super(), 'clean', None)
        if callable(parent_clean):
            parent_clean()

        if self.month and self.month.day != 1:
            raise ValidationError("Month must be the first day of the month.")

        tolerance = Decimal('0.01')
        zero = Decimal('0.00')

        advance_value = getattr(self, 'advance_deducted', zero)
        pf_value = getattr(self, 'pf_deduction', zero)
        esic_value = getattr(self, 'esic_deduction', zero)
        total_value = getattr(self, 'total_deductions', zero)
        gross_value = getattr(self, 'gross_pay', zero)
        net_value = getattr(self, 'net_pay', zero)

        advance_value = advance_value if advance_value is not None else zero
        pf_value = pf_value if pf_value is not None else zero
        esic_value = esic_value if esic_value is not None else zero
        total_value = total_value if total_value is not None else zero
        gross_value = gross_value if gross_value is not None else zero
        net_value = net_value if net_value is not None else zero

        expected_total = advance_value + pf_value + esic_value
        if abs(total_value - expected_total) > tolerance:
            raise ValidationError({
                'total_deductions': 'total_deductions must equal advance_deduction + pf_deduction + esic_deduction.'
            })

        expected_net = gross_value - total_value
        if abs(net_value - expected_net) > tolerance:
            raise ValidationError({
                'net_pay': 'net_pay must equal gross_pay minus total_deductions.'
            })

    def __str__(self):
        return f"{self.employee.name} - {self.month.strftime('%B %Y')}"

    # ⬇️ FIX 2 & 3: Lowercase 'self' and Correct Indentation
    def save(self, *args, **kwargs):
        """
        Auto-sets paid_on to today when salary is marked as paid
        and no payment date has been explicitly provided.
        """
        
        if self.is_paid and not self.paid_on:
            self.paid_on = timezone.now().date()

        
        super().save(*args, **kwargs)